title: [James Nisky]
description: |
  Growth Marketing Specialist, Account Based Marketing
  Enterprise AI, Cloud, Data, Analytics, B2B SaaS, Platforms, Innovation, Emerging Technology
theme: jekyll-theme-minimal

