title: [James Nisky]
description: > # this means to ignore newlines until "end"
Growth Marketing Specialist, Account Based Marketing

Enterprise AI, Cloud, Data, Analytics, B2B SaaS, Platforms, Innovation, Emerging Technology
theme: jekyll-theme-minimal
