title: [James Nisky]
description: |
  Growth Marketing Specialist, Account Based Marketing
  <br>
  Enterprise AI
  <br>
  Cloud
  <br>
  Data
  <br>
  Analytics
  <br>
  B2B SaaS
  <br>
  Platforms
  <br>
  Innovation
  <br>
  Emerging Technology
theme: jekyll-theme-minimal
